
steps:
- name: 'ubuntu'
  args: [ "echo", "hello Max\n${_BUILD_ID_YAML}\n${_PROJECT_ID_FROM_TRIGGER}\n{$_COMPARE_URL}"]
substitutions:
    _UPPER_OWNER: ${_OWNER_MUNGED^^}
    _BUILD_ID_YAML: what-a-${BUILD_ID:1:5}-build-id!!!!
    _PROJECT_ID_YAML: ${PROJECT_ID^^}
    _COMPARE_URL: $(push.compare)

