
steps:
- name: 'ubuntu'
  args: [ "echo", "hello Max\n${_BUILD_ID_YAML}\n${_PROJECT_ID_FROM_TRIGGER}\n{$_COMPARE_URL}"]
substitutions:
    _UPPER_OWNER: ${_OWNER_FROM_TRIGGER^^}
    _BUILD_ID_YAML: ${BUILD_ID:1:5}
    _PROJECT_ID_YAML: ${PROJECT_ID^^}
    _COMPARE_URL: $(push.compare)

