
steps:
- name: 'ubuntu'
  args: [ "echo", "BUILD_ID: ${BUILD_ID}\nBUILD_MUNGED: ${_BUILD_MUNGED}\nOwner:\n${_OWNER}\nupper case:\n${_UPPER_OWNER}\ncombined:\n${_COMBINED}"]
substitutions:
    _UPPER_OWNER: ${_OWNER^^}
    _COMBINED: my-app-${_UPPER_OWNER:1:3}-prod
    _BUILD_MUNGED: ${BUILD_ID:3:5}
