
steps:
- name: 'ubuntu'
  args: [ "echo", "hello foobar to for fetched_Data seafarer. \n${_BUILD_ID_YAML}\n${_PROJECT_ID_FROM_TRIGGER}\n{$_COMPARE_URL}\nemail:${_JSON_FILTER}"]
  id: 'break_me'
- name: 'ubuntu'
  args: [ "echo", "nonsense"]
  id: 'break_me'
substitutions:
    _UPPER_OWNER: ${_OWNER_MUNGED^^}
    _BUILD_ID_YAML: what-a-${BUILD_ID:1:5}-build-id!!!!
    _PROJECT_ID_YAML: ${PROJECT_ID^^}
    _COMPARE_URL: $(push.compare)
    _JSON_FILTER: $(push.commits[?(@.author.username=="car409")].author.email)
options:
    dynamic_substitutions: true
    worker_pool: "projects/creich-test/locations/us-west1/workerPools/worker-pool"
